export const PORTFOLIO_LIST_REQUEST = 'PORTFOLIO_LIST_REQUEST';
export const PORTFOLIO_LIST_SUCCESS = 'PORTFOLIO_LIST_SUCCESS';
export const PORTFOLIO_LIST_FAIL = 'PORTFOLIO_LIST_FAIL';

export const PORTFOLIO_DETAILS_REQUEST = 'PORTFOLIO_DETAILS_REQUEST';
export const PORTFOLIO_DETAILS_SUCCESS = 'PORTFOLIO_DETAILS_SUCCESS';
export const PORTFOLIO_DETAILS_FAIL = 'PORTFOLIO_DETAILS_FAIL';

export const PORTFOLIO_WIDGET_REQUEST = 'PORTFOLIO_WIDGET_REQUEST';
export const PORTFOLIO_WIDGET_SUCCESS = 'PORTFOLIO_WIDGET_SUCCESS';
export const PORTFOLIO_WIDGET_FAIL = 'PORTFOLIO_WIDGET_FAIL';