export const PARAMETER_DETAILS_REQUEST = 'PARAMETER_DETAILS_REQUEST';
export const PARAMETER_DETAILS_SUCCESS = 'PARAMETER_DETAILS_SUCCESS';
export const PARAMETER_DETAILS_FAIL = 'PARAMETER_DETAILS_FAIL';
