version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install --legacy-peer-deps
      - echo "📦 installing Front-end packages..."
      - echo "✅ Packages Front-end installed successfully."
  build:
    commands:
      - npm run build || true
      - echo "⚙️ Testing..."
      - echo "✅ Tests passed successfully."
      - echo "🚧 Starting Front-end compiling packages..."
      - echo "✅ Build Front-end passed successfully."
artifacts:
  files:
    - build/**/*
