export const ARCHITECT_LIST_REQUEST = 'ARCHITECT_LIST_REQUEST';
export const ARCHITECT_LIST_SUCCESS = 'ARCHITECT_LIST_SUCCESS';
export const ARCHITECT_LIST_FAIL = 'ARCHITECT_LIST_FAIL';

export const ARCHITECT_DETAILS_REQUEST = 'ARCHITECT_DETAILS_REQUEST';
export const ARCHITECT_DETAILS_SUCCESS = 'ARCHITECT_DETAILS_SUCCESS';
export const ARCHITECT_DETAILS_FAIL = 'ARCHITECT_DETAILS_FAIL';

export const ARCHITECT_WIDGET_REQUEST = 'ARCHITECT_WIDGET_REQUEST';
export const ARCHITECT_WIDGET_SUCCESS = 'ARCHITECT_WIDGET_SUCCESS';
export const ARCHITECT_WIDGET_FAIL = 'ARCHITECT_WIDGET_FAIL';