export const HEADER_LIST_REQUEST = 'HEADER_LIST_REQUEST';
export const HEADER_LIST_SUCCESS = 'HEADER_LIST_SUCCESS';
export const HEADER_LIST_FAIL = 'HEADER_LIST_FAIL';

export const HEADER_ZERO_REQUEST = 'HEADER_ZERO_REQUEST';
export const HEADER_ZERO_SUCCESS = 'HEADER_ZERO_SUCCESS';
export const HEADER_ZERO_FAIL = 'HEADER_ZERO_FAIL';

export const HEADER_ONE_REQUEST = 'HEADER_ONE_REQUEST';
export const HEADER_ONE_SUCCESS = 'HEADER_ONE_SUCCESS';
export const HEADER_ONE_FAIL = 'HEADER_ONE_FAIL';