export const IMAGE_CAROUSEL_REQUEST = 'IMAGE_CAROUSEL_REQUEST';
export const IMAGE_CAROUSEL_SUCCESS = 'IMAGE_CAROUSEL_SUCCESS';
export const IMAGE_CAROUSEL_FAIL = 'IMAGE_CAROUSEL_FAIL';

export const IMAGE_WIDGET_REQUEST = 'IMAGE_WIDGET_REQUEST';
export const IMAGE_WIDGET_SUCCESS = 'IMAGE_WIDGET_SUCCESS';
export const IMAGE_WIDGET_FAIL = 'IMAGE_WIDGET_FAIL';