export const IMAGE_CAROUSEL_REQUEST = 'IMAGE_CAROUSEL_REQUEST';
export const IMAGE_CAROUSEL_SUCCESS = 'IMAGE_CAROUSEL_SUCCESS';
export const IMAGE_CAROUSEL_FAIL = 'IMAGE_CAROUSEL_FAIL';

export const IMAGE_PHOTO_REQUEST = 'IMAGE_PHOTO_REQUEST';
export const IMAGE_PHOTO_SUCCESS = 'IMAGE_PHOTO_SUCCESS';
export const IMAGE_PHOTO_FAIL = 'IMAGE_PHOTO_FAIL';
