name: GitHub Actions
on:
  push:
    branches: [ maryan ]
  pull_request:
    branches: [ maryan ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
      - name: lint code
        run: npm run lint
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          name: id_rsa # optional
          known_hosts: unnecessary

      - run: chmod 644 ~/.ssh/id_rsa
      - run: cat ~/.ssh/id_rsa
        run: chmod 644 ~/.ssh/known_hosts
      - name: Adding Known Hosts
     -  run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - run: cat ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz ./ root@95.217.167.13:/home/marian/woodhouse-app/
        #run: rsync -avz -e "ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" root@95.217.167.13:/home/marian/woodhouse-app/




