name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: test app
        run: npm run lint
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: chmod 0700 "$HOME/.ssh"
      - run: echo "${{ secrets.ID_RSAGIT }}" > "$HOME/.ssh/id_rsagit"
      - run: chmod 0644 "$HOME/.ssh/id_rsagit"
      - run: service sshd restart
      - run: ssh -i $HOME/.ssh/id_rsagit -p 22 root@95.217.167.13
      # Build
      - run: npm ci
      - run: npm run build
      # Deploy
      - run: rsync -avz -e "ssh -p 22 -i $HOME/.ssh/id_rsagit -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress root@95.217.167.13:/home/marian/woodhose-app
